version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: hotel-booking-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE:-hotel_booking_db}
    networks:
      - hotel-network

  app:
    build: .
    container_name: hotel-booking-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker  # Указываем профиль
      - MONGODB_HOST=mongodb           # Передаем в приложение
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - BCRYPT_STRENGTH=${BCRYPT_STRENGTH:-10}
    networks:
      - hotel-network
    depends_on:
      - mongodb

volumes:
  mongo_data:

networks:
  hotel-network: